name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:

  build:
    name: build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install pypa/build tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: Build distribution
        run: |
          python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  github:
    name: publish to github
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout tag
        uses: actions/checkout@v5
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
        with:
          prerelease: false
          generateReleaseNotes: "true"
          assets: |
            - path: dist/*

  pypi:
    name: publish to pypi
    runs-on: ubuntu-latest
    needs:
      - build
      - github
    environment:
      name: pypi
      url: https://pypi.org/p/qiskit-addon-utils
    permissions:
      id-token: write
    steps:
      - name: Checkout tag
        uses: actions/checkout@v5
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
