name: Development version tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    name: development version tests (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Determine development versions
        shell: bash
        run: |
          # NOTE: by determining the current git commit SHAs, we can ensure that
          # the individually run tox environments indeed actually use the exact
          # same versions (which may not be the case if at the exact time a new
          # commit gets added to the respective repositories).
          # Additionally, using these commit SHAs ensures that the locally built
          # Python wheels get cached, ensuring a faster tox environment setup
          # for the multiple jobs below.
          QISKIT_SHA=$(git ls-remote "https://github.com/Qiskit/qiskit" | grep HEAD | awk '{print $1}')
          echo "QISKIT_SHA=$QISKIT_SHA" >> "$GITHUB_ENV"
          echo "Using Qiskit/qiskit @ $QISKIT_SHA"
          QISKIT_IBM_RUNTIME_SHA=$(git ls-remote "https://github.com/Qiskit/qiskit-ibm-runtime" | grep HEAD | awk '{print $1}')
          echo "QISKIT_IBM_RUNTIME_SHA=$QISKIT_IBM_RUNTIME_SHA" >> "$GITHUB_ENV"
          echo "Using Qiskit/qiskit-ibm-runtime @ $QISKIT_IBM_RUNTIME_SHA"
      - name: Pinning development versions
        shell: bash
        run: |
          python -m pip install --upgrade pip
      - name: Install tools from pypi
        run: |
          python -m pip install tox build extremal-python-dependencies==0.0.3
      - name: Build Qiskit SDK development wheel
        run: |
          git clone https://github.com/Qiskit/qiskit
          cd qiskit
          git rev-parse HEAD
          python -m build --wheel
      - name: Build qiskit-ibm-runtime development wheel
        run: |
          git clone https://github.com/Qiskit/qiskit-ibm-runtime
          cd qiskit-ibm-runtime
          git rev-parse HEAD
          python -m build --wheel
      - name: Pin development versions
        shell: bash
        run: >-
          extremal-python-dependencies pin-dependencies --inplace
          "qiskit @ file:$(realpath qiskit/dist/*.whl)"
          "qiskit-ibm-runtime @ file:$(realpath qiskit-ibm-runtime/dist/*.whl)"
      - name: Test using tox environment
        shell: bash
        run: |
          tox -e py,notebook,doctest
